name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'temurin'

      - name: gradle check
        run: ./gradlew check assembleDebug

  
